apiVersion: skaffold/v1alpha4
kind: Config
build:
  artifacts:
    - image: eu.gcr.io/dcos-145910/messageapp
      context: ./messageapp/
    - image: eu.gcr.io/dcos-145910/messagebackend
      context: ./messagebackend/
    - image: eu.gcr.io/dcos-145910/messageredisconsumer
      context: ./messageredisconsumer/
    - image: eu.gcr.io/dcos-145910/ui2
      context: ./ui2/
  tagPolicy:
    sha256: {}
  local:
    push: false
deploy:
  helm:
    releases:
      - name: bigdemo
        chartPath: bigdemo
        values:
          messageapp.image: eu.gcr.io/dcos-145910/messageapp
          messagebackend.image: eu.gcr.io/dcos-145910/messagebackend
          messageredisconsumer.image: eu.gcr.io/dcos-145910/messageredisconsumer
          ui2.image: eu.gcr.io/dcos-145910/ui2
# profiles section has all the profile information which can be used to override any build or deploy configuration
profiles:
  - name: gke
    build:
      googleCloudBuild:
        projectId: "dcos-145910"
        diskSizeGb: 200
        machineType: "N1_HIGHCPU_8"
      tagPolicy:
        dateTime:
          format: "2006-01-02"
          timezone: "UTC"
    deploy:
      helm:
        releases:
          - name: bigdemo
            chartPath: bigdemo
            values:
              messageapp.image: eu.gcr.io/dcos-145910/messageapp
              messagebackend.image: eu.gcr.io/dcos-145910/messagebackend
              messageredisconsumer.image: eu.gcr.io/dcos-145910/messageredisconsumer
              ui2.image: eu.gcr.io/dcos-145910/ui2
            overrides:
              ingress:
                hosts:
                  - bigdemo.alexkrieg.de
