apiVersion: skaffold/v1alpha4
kind: Config
build:
  artifacts:
  - image: messageapp
    context: ./messageapp/
  - image: messagebackend
    context: ./messagebackend/
  - image: messageredisconsumer
    context: ./messageredisconsumer/
  - image: ui2
    context: ./ui2/
  tagPolicy:
    sha256: {}
  local:
    push: false
deploy:
  helm:
    releases:
    - name: bigdemo
      chartPath: bigdemo
      valuesFiles:
      - ./bigdemo-values.yaml
      values:
        messageapp.image: messageapp
        messagebackend.image: messagebackend
        messageredisconsumer.image: messageredisconsumer
        ui2.image: ui2