apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
    - image: eu.gcr.io/dcos-145910/messageapp
      context: ./messageapp/
    - image: eu.gcr.io/dcos-145910/messagebackend
      context: ./messagebackend/
    - image: eu.gcr.io/dcos-145910/messageredisconsumer
      context: ./messageredisconsumer/
    - image: eu.gcr.io/dcos-145910/ui2
      context: ./ui2/
  local:
    push: false
deploy:
  helm:
    releases:
      - name: bigdemo
        chartPath: bigdemo
        values: 
          messageapp.image: eu.gcr.io/dcos-145910/messageapp
          ui2.image: eu.gcr.io/dcos-145910/ui2
          messagebackend.image: eu.gcr.io/dcos-145910/messagebackend
          messageredisconsumer.image: eu.gcr.io/dcos-145910/messageredisconsumer

# profiles section has all the profile information which can be used to override any build or deploy configuration
profiles:
  - name: gke
    build:
      googleCloudBuild:
        projectId: "dcos-145910"
        diskSizeGb: 200
        machineType: "N1_HIGHCPU_32"
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}:{{.RELEASE}}"
    deploy:
      helm:
        releases:
          - name: bigdemo
            chartPath: bigdemo
            values: 
              messageapp.image: eu.gcr.io/dcos-145910/messageapp
              ui2.image: eu.gcr.io/dcos-145910/ui2
              messagebackend.image: eu.gcr.io/dcos-145910/messagebackend
              messageredisconsumer.image: eu.gcr.io/dcos-145910/messageredisconsumer
            valuesFiles:
              - bigdemo-gke-values.yaml
