apiVersion: skaffold/v1alpha3
kind: Config
build:
  artifacts:
  - imageName: messageapp
    workspace: ./messageapp/
  - imageName: messagebackend
    workspace: ./messagebackend/
  - imageName: messageredisconsumer
    workspace: ./messageredisconsumer/
  - imageName: ui2
    workspace: ./ui2/
  tagPolicy:
    sha256: {}
  local:
    skipPush: true
deploy:
  helm:
    releases:
    - name: bigdemo
      chartPath: bigdemo
      valuesFiles:
      - ./bigdemo-values.yaml
      values:
        messageapp.image: messageapp
        messagebackend.image: messagebackend
        messageredisconsumer.image: messageredisconsumer
        ui2.image: ui2
      namespace: ""
      version: ""
      setValues: {}
      setValueTemplates: {}
      wait: false
      recreatePods: false
      overrides: {}
      packaged: null
      imageStrategy:
        fqn: null
        helm: null