apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "messageapp.fullname" . }}
  labels:
    app: {{ template "messageapp.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.messageapp.replicaCount }}
  template:
    metadata:
      name: {{ template "messageapp.fullname" . }}
      labels:
        app: {{ template "messageapp.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "messageapp.fullname" . }}
          image: {{ .Values.messageapp.image }}
          imagePullPolicy: {{ .Values.messageapp.pullPolicy }}
          env:
            - name: RABBITMQ_HOST
              value: {{ .Release.Name }}-rabbitmq
            - name: RABBITMQ_USER
              value: {{ .Values.rabbitmq.rabbitmq.user }}
            - name: RABBITMQ_PASSWORD
              value: {{ .Values.rabbitmq.rabbitmq.password | quote }}
            - name: RABBITMQ_MESSAGE_EXCHANGE
              value: {{ .Values.messageapp.rabbitmq.exchange }}
            - name: BASE_URL
              value: "http://{{ index .Values.ingress.hosts 0 }}"

          ports:
          - name: http
            containerPort: 8080
          resources:
{{ toYaml .Values.messageapp.resources | indent 12 }}
    {{- if .Values.messageapp.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.messageapp.nodeSelector | indent 8 }}
    {{- end }}
