apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "messagebackend.fullname" . }}
  labels:
    app: {{ template "messagebackend.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.messagebackend.replicaCount }}
  template:
    metadata:
      name: {{ template "messagebackend.fullname" . }}
      labels:
        app: {{ template "messagebackend.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "messagebackend.fullname" . }}
          image: {{ .Values.messagebackend.image }}
          imagePullPolicy: {{ .Values.messagebackend.pullPolicy }}
          env:
            - name: REDIS_HOST
              value: {{ .Release.Name }}-redis-master
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.password }}
          ports:
          - name: http
            containerPort: 8000
          resources:
{{ toYaml .Values.messagebackend.resources | indent 12 }}
    {{- if .Values.messagebackend.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.messagebackend.nodeSelector | indent 8 }}
    {{- end }}
