apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "messageredisconsumer.fullname" . }}
  labels:
    app: {{ template "messageredisconsumer.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.messageredisconsumer.replicaCount }}
  template:
    metadata:
      name: {{ template "messageredisconsumer.fullname" . }}
      labels:
        app: {{ template "messageredisconsumer.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "messageredisconsumer.fullname" . }}
          image: {{ .Values.messageredisconsumer.image }}
          imagePullPolicy: {{ .Values.messageredisconsumer.pullPolicy }}
          env:
            - name: RABBITMQ_HOST
              value: {{ .Release.Name }}-rabbitmq
            - name: RABBITMQ_USER
              value: {{ .Values.rabbitmq.rabbitmq.user }}
            - name: RABBITMQ_PASSWORD
              value: {{ .Values.rabbitmq.rabbitmq.password | quote }}
            - name: RABBITMQ_MESSAGE_QUEUE
              value: {{ .Values.messageredisconsumer.rabbitmq.queue }}
            - name: RABBITMQ_EXCHANGE
              value: {{ .Values.messageapp.rabbitmq.exchange }}
          ports:
          - name: http
            containerPort: 8000
          resources:
{{ toYaml .Values.messageredisconsumer.resources | indent 12 }}
    {{- if .Values.messageredisconsumer.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.messageredisconsumer.nodeSelector | indent 8 }}
    {{- end }}
