# requirements.yaml
dependencies:
  - name: nginx-ingress
    version: " 0.23.0"
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: keycloak
    version: "3.1.0"
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: rabbitmq
    version: "3.5.1"
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: redis
    version: "3.7.3"
    repository: https://kubernetes-charts.storage.googleapis.com/
