# requirements.yaml
dependencies:
  - name: nginx-ingress
    version: "1.3.1"
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: rabbitmq
    version: "3.5.1"
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: redis
    version: "3.7.3"
    repository: https://kubernetes-charts.storage.googleapis.com/
